CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL CHECK(role IN ('ADMIN', 'CAJERO')),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS shifts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  caja_inicial REAL NOT NULL,
  start_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  end_at DATETIME,
  tot_efectivo REAL DEFAULT 0,
  tot_qr REAL DEFAULT 0,
  gastos REAL DEFAULT 0,
  FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS inventory_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nombre TEXT NOT NULL,
  contenido_gramos REAL,
  peso_envase_gramos REAL,
  modo_stock TEXT NOT NULL CHECK(modo_stock IN ('GRAMOS', 'UNIDADES')),
  stock REAL NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nombre TEXT NOT NULL,
  precio REAL NOT NULL,
  tipo TEXT NOT NULL CHECK(tipo IN ('BOTELLA', 'JARRA', 'SHOT', 'VASO', 'PACK', 'PROMOCION', 'OTROS')),
  imagen_path TEXT,
  activo INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS product_components (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  product_id INTEGER NOT NULL,
  inventory_item_id INTEGER NOT NULL,
  cantidad REAL NOT NULL,
  FOREIGN KEY(product_id) REFERENCES products(id),
  FOREIGN KEY(inventory_item_id) REFERENCES inventory_items(id)
);

CREATE TABLE IF NOT EXISTS sales (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  fecha DATETIME DEFAULT CURRENT_TIMESTAMP,
  user_id INTEGER NOT NULL,
  shift_id INTEGER NOT NULL,
  total REAL NOT NULL,
  metodo_pago TEXT NOT NULL CHECK(metodo_pago IN ('EFECTIVO', 'QR', 'MIXTO')),
  FOREIGN KEY(user_id) REFERENCES users(id),
  FOREIGN KEY(shift_id) REFERENCES shifts(id)
);

CREATE TABLE IF NOT EXISTS sale_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  sale_id INTEGER NOT NULL,
  product_id INTEGER NOT NULL,
  cantidad INTEGER NOT NULL,
  precio_unitario REAL NOT NULL,
  subtotal REAL NOT NULL,
  FOREIGN KEY(sale_id) REFERENCES sales(id),
  FOREIGN KEY(product_id) REFERENCES products(id)
);

CREATE TABLE IF NOT EXISTS payments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  sale_id INTEGER NOT NULL,
  efectivo REAL DEFAULT 0,
  qr REAL DEFAULT 0,
  FOREIGN KEY(sale_id) REFERENCES sales(id)
);

CREATE TABLE IF NOT EXISTS expenses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  shift_id INTEGER NOT NULL,
  monto REAL NOT NULL,
  referencia TEXT NOT NULL,
  fecha DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(shift_id) REFERENCES shifts(id)
);

CREATE TABLE IF NOT EXISTS tables (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nombre TEXT NOT NULL,
  color_rgb TEXT NOT NULL,
  rect_x REAL NOT NULL,
  rect_y REAL NOT NULL,
  rect_w REAL NOT NULL,
  rect_h REAL NOT NULL,
  estado TEXT NOT NULL DEFAULT 'LIBRE' CHECK(estado IN ('LIBRE', 'OCUPADO'))
);

CREATE TABLE IF NOT EXISTS table_links (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  table_id INTEGER NOT NULL,
  token_base64 TEXT NOT NULL,
  url TEXT NOT NULL,
  FOREIGN KEY(table_id) REFERENCES tables(id)
);

CREATE TABLE IF NOT EXISTS chat_messages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  table_id INTEGER NOT NULL,
  message TEXT NOT NULL,
  from_role TEXT NOT NULL CHECK(from_role IN ('MESA', 'DJ', 'CAJERO')),
  ts DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(table_id) REFERENCES tables(id)
);

CREATE TABLE IF NOT EXISTS playlist (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  table_id INTEGER NOT NULL,
  title TEXT NOT NULL,
  youtube_id TEXT NOT NULL,
  tipo TEXT NOT NULL CHECK(tipo IN ('CANCION', 'KARAOKE')),
  estado TEXT NOT NULL DEFAULT 'PENDIENTE' CHECK(estado IN ('PENDIENTE', 'HECHA')),
  ts DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(table_id) REFERENCES tables(id)
);

CREATE TABLE IF NOT EXISTS settings (
  clave TEXT PRIMARY KEY,
  valor_json TEXT NOT NULL
);
